#!/bin/bash

if [ $# -ne 2 ]; then
    echo "Uso: $0 <nombre_usuario> <nombre_grupo>"
    exit 1
fi

nuevo_usuario="$1"
nuevo_grupo="$2"

# Verificar si el usuario ya existe
if id "$nuevo_usuario" &>/dev/null; then
    echo "El usuario '$nuevo_usuario' ya existe."
else
    # Crear el nuevo usuario
    sudo useradd "$nuevo_usuario"
    echo "Usuario '$nuevo_usuario' creado con éxito."
fi

# Verificar si el grupo ya existe
if grep -q "^$nuevo_grupo:" /etc/group; then
    echo "El grupo '$nuevo_grupo' ya existe."
else
    # Crear el nuevo grupo
    sudo groupadd "$nuevo_grupo"
    echo "Grupo '$nuevo_grupo' creado con éxito."
fi

# Agregar el usuario default y el nuevo usuario al grupo
sudo usermod -aG "$nuevo_grupo" "$USER"
sudo usermod -aG "$nuevo_grupo" "$nuevo_usuario"

# Asignar permisos de ejecución al script para miembros del grupo
chmod g+x get_permissions.sh
sudo chown :"$nuevo_grupo" get_permissions.sh
